// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_5faFBe6K7URAE9WqNehlY-FPzcBVBew',
    appId: '1:907940115023:web:46b43071e42aed3971b03a',
    messagingSenderId: '907940115023',
    projectId: 'voicematch-45289',
    authDomain: 'voicematch-45289.firebaseapp.com',
    storageBucket: 'voicematch-45289.appspot.com',
    measurementId: 'G-9VLGVT24TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBUv8iAbMPm0vNRTXDcKsOwU9EbFLUedw',
    appId: '1:907940115023:android:bdb507c80dab292d71b03a',
    messagingSenderId: '907940115023',
    projectId: 'voicematch-45289',
    storageBucket: 'voicematch-45289.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQcbNnM1vXf6zl0__WxMHJma90m60muj4',
    appId: '1:907940115023:ios:4bedae785ad2c4ca71b03a',
    messagingSenderId: '907940115023',
    projectId: 'voicematch-45289',
    storageBucket: 'voicematch-45289.appspot.com',
    iosClientId: '907940115023-n4da9hrvq88i3o2hpf9lrjmlui57nuce.apps.googleusercontent.com',
    iosBundleId: 'com.voicevibe.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQcbNnM1vXf6zl0__WxMHJma90m60muj4',
    appId: '1:907940115023:ios:4bedae785ad2c4ca71b03a',
    messagingSenderId: '907940115023',
    projectId: 'voicematch-45289',
    storageBucket: 'voicematch-45289.appspot.com',
    iosClientId: '907940115023-n4da9hrvq88i3o2hpf9lrjmlui57nuce.apps.googleusercontent.com',
    iosBundleId: 'com.voicevibe.app',
  );
}
